language: android

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-17

env:
  global:
    - INSTALL_PKGS='build-tools-21.1.2'
    - UPDATE_PKGS='platform-tools,tools,extra-android-m2repository,extra-google-m2repository'
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - AVD_DEBUG='init,avd_config,nand_limits,keys,adb,adbserver,adbclient'
    - ANDROID_LOG_TAGS='NetworkStats:S dalvikvm:S Zygote:S Resources:S *:D'
    - ANDROID_SERIAL='emulator-5554'
    - ANDROID_HOME='/usr/local/android-sdk'
    - PATH="${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}"

before_install:
 - chmod +x gradlew
 - ./execute inexistent install-and-update-sdk
 - ./execute create-and-start-device wait-for-device-online

install:
 - ./gradlew --version # show version and download Gradle Wrapper when is not present in cache
 - ./gradlew clean # clean project and download Android dependencies when are not present in cache
 - ./gradlew assemble

 # Emulator Management: Create, Start and Wait
before_script:
 - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - adb wait-for-device
 - adb shell input keyevent 82 &

script:
 - echo $ADB_INSTALL_TIMEOUT
 - android list target
 - ./gradlew test connectedAndroidTest

after_script:
 - cat ${TRAVIS_BUILD_DIR}/espresso/*/app/build/outputs/androidTest-results/connected/* # show logs